package de.giaphongtran.unicaragil.ehmi;

public enum Command {
	FAHRZEUG_WIRD_GELADEN,
	AUSPARKEN_RECHTS,
	AUSPARKEN_LINKS,
	ENGSTELLE_BEIDSEITIG,
	ENGSTELLE_BEIDSEITIG_DISTANZ, //TODO
	ZEBRASTREIFEN,
	ZEBRASTREIFEN_DISTANZ,
	EMERGENCY,
	WENDE_RECHTS,
	WENDE_RECHTS_GEPLANT,
	WENDE_LINKS,
	WENDE_LINKS_GEPLANT,
	WENDE_BEENDET,
	EINPARKEN_RECHTS,
	EINPARKEN_LINKS,
	EINPARKEN_FERTIG,
	EINPARKEN_ABBRECHEN,
}
